<?php

// Register Custom Post Type
function custom_post_type()
{

	$action_item_labels = array(
		'name'                  => 'Action Items',
		'singular_name'         => 'Action Item',
		'menu_name'             => 'Action Items',
		'name_admin_bar'        => 'Action Item',
		'archives'              => 'Action Item Archives',
		'attributes'            => 'Action Item Attributes',
		'parent_item_colon'     => 'Parent Action Item:',
		'all_items'             => 'All Action Items',
		'add_new_item'          => 'Add New Action Item',
		'add_new'               => 'Add Action Item',
		'new_item'              => 'New Action Item',
		'edit_item'             => 'Edit Action Item',
		'update_item'           => 'Update Action Item',
		'view_item'             => 'View Action Item',
		'view_items'            => 'View Action Items',
		'search_items'          => 'Search Action Item',
		'not_found'             => 'Not found',
		'not_found_in_trash'    => 'Not found in Trash',
		'featured_image'        => 'Featured Image',
		'set_featured_image'    => 'Set featured image',
		'remove_featured_image' => 'Remove featured image',
		'use_featured_image'    => 'Use as featured image',
		'insert_into_item'      => 'Insert into action item',
		'uploaded_to_this_item' => 'Uploaded to this action item',
		'items_list'            => 'Action Items list',
		'items_list_navigation' => 'Action Items list navigation',
		'filter_items_list'     => 'Filter action items list',
	);

	$action_item_args = array(
		'rewrite'				=> array('slug' => 'actionitems'),
		'label'                 => 'Action Item',
		'description'           => 'This post type will hold the details of all the actionable items for Apartment',
		'labels'                => $action_item_labels,
		'supports'              => array('title', 'editor', 'thumbnail', 'comments', 'revisions', 'custom-fields', 'page-attributes', 'excerpt'),
		'taxonomies'            => array('category', 'post_tag', 'actionitem'),
		'hierarchical'          => false,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'actionitem',
		'map_meta_cap'			=> true,
		'menu_icon'				=> 'dashicons-hammer',
		'show_in_rest'          => true, // WP Block Editor
		// 'rest_controller_class' => 'WP_REST_ActionItems_Controller',
	);

	$transaction_labels = array(
		'name'                  => 'Transactions',
		'singular_name'         => 'Transaction',
		'menu_name'             => 'Transactions',
		'name_admin_bar'        => 'Transaction',
		'archives'              => 'Transaction Archives',
		'attributes'            => 'Transaction Attributes',
		'parent_item_colon'     => 'Parent Transaction:',
		'all_items'             => 'All Transactions',
		'add_new_item'          => 'Add New Transaction',
		'add_new'               => 'Add Transaction',
		'new_item'              => 'New Transaction',
		'edit_item'             => 'Edit Transaction',
		'update_item'           => 'Update Transaction',
		'view_item'             => 'View Transaction',
		'view_items'            => 'View Transactions',
		'search_items'          => 'Search Transaction',
		'not_found'             => 'Not found',
		'not_found_in_trash'    => 'Not found in Trash',
		'featured_image'        => 'Featured Image',
		'set_featured_image'    => 'Set featured image',
		'remove_featured_image' => 'Remove featured image',
		'use_featured_image'    => 'Use as featured image',
		'insert_into_item'      => 'Insert into transaction',
		'uploaded_to_this_item' => 'Uploaded to this transaction',
		'items_list'            => 'Transactions list',
		'items_list_navigation' => 'Transactions list navigation',
		'filter_items_list'     => 'Filter transactions list',
	);

	$transaction_args = array(
		'rewrite'				=> array('slug' => 'transactions'),
		'label'                 => 'Transaction',
		'description'           => 'This post type will hold the details of all the transactions for Apartment',
		'labels'                => $transaction_labels,
		'supports'              => array('title', 'editor', 'thumbnail', 'comments', 'revisions', 'custom-fields', 'page-attributes', 'excerpt'),
		'taxonomies'            => array('category', 'post_tag', 'transaction'),
		'hierarchical'          => false,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'transaction',
		'map_meta_cap'			=> true,
		'menu_icon'				=> 'dashicons-list-view',
		'show_in_rest'          => true, // WP Block Editor
		// 'rest_controller_class' => 'WP_REST_ActionItems_Controller',
	);

	$passbook_labels = array(
		'name'                  => 'Passbook Entries',
		'singular_name'         => 'Passbook Entry',
		'menu_name'             => 'Passbook Entries',
		'name_admin_bar'        => 'Passbook Entry',
		'archives'              => 'Passbook Entry Archives',
		'attributes'            => 'Passbook Entry Attributes',
		'parent_item_colon'     => 'Parent Passbook Entry:',
		'all_items'             => 'All Passbook Entries',
		'add_new_item'          => 'Add New Passbook Entry',
		'add_new'               => 'Add Passbook Entry',
		'new_item'              => 'New Passbook Entry',
		'edit_item'             => 'Edit Passbook Entry',
		'update_item'           => 'Update Passbook Entry',
		'view_item'             => 'View Passbook Entry',
		'view_items'            => 'View Passbook Entries',
		'search_items'          => 'Search Passbook Entry',
		'not_found'             => 'Not found',
		'not_found_in_trash'    => 'Not found in Trash',
		'featured_image'        => 'Featured Image',
		'set_featured_image'    => 'Set featured image',
		'remove_featured_image' => 'Remove featured image',
		'use_featured_image'    => 'Use as featured image',
		'insert_into_item'      => 'Insert into Passbook Entry',
		'uploaded_to_this_item' => 'Uploaded to this Passbook Entry',
		'items_list'            => 'Passbook Entries list',
		'items_list_navigation' => 'Passbook Entries list navigation',
		'filter_items_list'     => 'Filter Passbook Entries list',
	);

	$passbook_args = array(
		'label'                 => 'Passbook Entry',
		'description'           => 'This post type will hold the details of all the passbook entries for Apartment',
		'labels'                => $passbook_labels,
		'supports'              => array('title', 'editor', 'thumbnail', 'comments', 'revisions', 'custom-fields', 'page-attributes', 'excerpt'),
		'taxonomies'            => array('category', 'post_tag', 'passbook'),
		'hierarchical'          => false,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'passbook',
		'map_meta_cap'			=> true,
		'menu_icon'				=> 'dashicons-text',
		'show_in_rest'          => true, // WP Block Editor
		// 'rest_controller_class' => 'WP_REST_ActionItems_Controller',
	);

	$bulletin_labels = array(
		'name'                  => 'Bulletins',
		'singular_name'         => 'Bulletin',
		'menu_name'             => 'Bulletins',
		'name_admin_bar'        => 'Bulletin',
		'archives'              => 'Bulletin Archives',
		'attributes'            => 'Bulletin Attributes',
		'parent_item_colon'     => 'Parent Bulletin:',
		'all_items'             => 'All Bulletins',
		'add_new_item'          => 'Add New Bulletin',
		'add_new'               => 'Add Bulletin',
		'new_item'              => 'New Bulletin',
		'edit_item'             => 'Edit Bulletin',
		'update_item'           => 'Update Bulletin',
		'view_item'             => 'View Bulletin',
		'view_items'            => 'View Bulletins',
		'search_items'          => 'Search Bulletin',
		'not_found'             => 'Not found',
		'not_found_in_trash'    => 'Not found in Trash',
		'featured_image'        => 'Featured Image',
		'set_featured_image'    => 'Set featured image',
		'remove_featured_image' => 'Remove featured image',
		'use_featured_image'    => 'Use as featured image',
		'insert_into_item'      => 'Insert into Bulletin',
		'uploaded_to_this_item' => 'Uploaded to this Bulletin',
		'items_list'            => 'Bulletins list',
		'items_list_navigation' => 'Bulletins list navigation',
		'filter_items_list'     => 'Filter Bulletins list',
	);

	$bulletin_args = array(
		'rewrite'				=> array('slug' => 'bulletins'),
		'label'                 => 'Bulletin',
		'description'           => 'This post type will hold the details of all the bulletins for Apartment',
		'labels'                => $bulletin_labels,
		'supports'              => array('title', 'editor', 'thumbnail', 'comments', 'revisions', 'custom-fields', 'page-attributes', 'excerpt'),
		'taxonomies'            => array('category', 'post_tag', 'bulletin'),
		'hierarchical'          => false,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'bulletin',
		'map_meta_cap'			=> true,
		'menu_icon'				=> 'dashicons-info',
		'show_in_rest'          => true, // WP Block Editor
		// 'rest_controller_class' => 'WP_REST_ActionItems_Controller',
	);

	$pending_payments_labels = array(
		'name'                  => 'Pending Payments',
		'singular_name'         => 'Pending Payment',
		'menu_name'             => 'Pending Payments',
		'name_admin_bar'        => 'Pending Payment',
		'archives'              => 'Pending Payment Archives',
		'attributes'            => 'Pending Payment Attributes',
		'parent_item_colon'     => 'Parent Pending Payment:',
		'all_items'             => 'All Pending Payments',
		'add_new_item'          => 'Add New Pending Payment',
		'add_new'               => 'Add Pending Payment',
		'new_item'              => 'New Pending Payment',
		'edit_item'             => 'Edit Pending Payment',
		'update_item'           => 'Update Pending Payment',
		'view_item'             => 'View Pending Payment',
		'view_items'            => 'View Pending Payments',
		'search_items'          => 'Search Pending Payment',
		'not_found'             => 'Not found',
		'not_found_in_trash'    => 'Not found in Trash',
		'featured_image'        => 'Featured Image',
		'set_featured_image'    => 'Set featured image',
		'remove_featured_image' => 'Remove featured image',
		'use_featured_image'    => 'Use as featured image',
		'insert_into_item'      => 'Insert into Pending Payment',
		'uploaded_to_this_item' => 'Uploaded to this Pending Payment',
		'items_list'            => 'Pending Payments list',
		'items_list_navigation' => 'Pending Payments list navigation',
		'filter_items_list'     => 'Filter Pending Payments list',
	);

	$pending_payments_args = array(
		'rewrite'				=> array('slug' => 'pending-payments'),
		'label'                 => 'Pending Payment',
		'description'           => 'This post type will hold the details of all the pending payments for Apartment',
		'labels'                => $pending_payments_labels,
		'supports'              => array('title', 'editor', 'thumbnail', 'comments', 'revisions', 'custom-fields', 'page-attributes', 'excerpt'),
		'taxonomies'            => array('category', 'post_tag', 'pending-payment'),
		'hierarchical'          => false,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'pending-payment',
		'map_meta_cap'			=> true,
		'menu_icon'				=> 'dashicons-backup',
		'show_in_rest'          => true, // WP Block Editor
		// 'rest_controller_class' => 'WP_REST_ActionItems_Controller',
	);

	$transaction_audit_labels = array(
		'name'                  => 'Transaction Audits',
		'singular_name'         => 'Transaction Audit',
		'menu_name'             => 'Transaction Audits',
		'name_admin_bar'        => 'Transaction Audit',
		'archives'              => 'Transaction Audit Archives',
		'attributes'            => 'Transaction Audit Attributes',
		'parent_item_colon'     => 'Parent Transaction Audit:',
		'all_items'             => 'All Transaction Audits',
		'add_new_item'          => 'Add New Transaction Audit',
		'add_new'               => 'Add Transaction Audit',
		'new_item'              => 'New Transaction Audit',
		'edit_item'             => 'Edit Transaction Audit',
		'update_item'           => 'Update Transaction Audit',
		'view_item'             => 'View Transaction Audit',
		'view_items'            => 'View Transaction Audits',
		'search_items'          => 'Search Transaction Audit',
		'not_found'             => 'Not found',
		'not_found_in_trash'    => 'Not found in Trash',
		'featured_image'        => 'Featured Image',
		'set_featured_image'    => 'Set featured image',
		'remove_featured_image' => 'Remove featured image',
		'use_featured_image'    => 'Use as featured image',
		'insert_into_item'      => 'Insert into Transaction Audit',
		'uploaded_to_this_item' => 'Uploaded to this Transaction Audit',
		'items_list'            => 'Transaction Audits list',
		'items_list_navigation' => 'Transaction Audits list navigation',
		'filter_items_list'     => 'Filter transactions list',
	);

	$transaction_audit_args = array(
		'label'                 => 'Transaction Audit',
		'description'           => 'This post type will hold the details of all the audit for transactions in Apartment',
		'labels'                => $transaction_audit_labels,
		'supports'              => array('title', 'editor', 'thumbnail', 'comments', 'revisions', 'custom-fields', 'page-attributes', 'excerpt'),
		'taxonomies'            => array('category', 'post_tag', 'transaction-audit'),
		'hierarchical'          => false,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => false,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => true,
		'publicly_queryable'    => true,
		'capability_type'       => 'transaction-audit',
		'map_meta_cap'			=> true,
		'menu_icon'				=> 'dashicons-admin-links',
		'show_in_rest'          => false, // WP Block Editor
		// 'rest_controller_class' => 'WP_REST_ActionItems_Controller',
	);

	$maintenance_record_labels = array(
		'name'                  => 'Maintenance Records',
		'singular_name'         => 'Maintenance Record',
		'menu_name'             => 'Maintenance Records',
		'name_admin_bar'        => 'Maintenance Record',
		'archives'              => 'Maintenance Record Archives',
		'attributes'            => 'Maintenance Record Attributes',
		'parent_item_colon'     => 'Parent Maintenance Record:',
		'all_items'             => 'All Maintenance Records',
		'add_new_item'          => 'Add New Maintenance Record',
		'add_new'               => 'Add Maintenance Record',
		'new_item'              => 'New Maintenance Record',
		'edit_item'             => 'Edit Maintenance Record',
		'update_item'           => 'Update Maintenance Record',
		'view_item'             => 'View Maintenance Record',
		'view_items'            => 'View Maintenance Records',
		'search_items'          => 'Search Maintenance Record',
		'not_found'             => 'Not found',
		'not_found_in_trash'    => 'Not found in Trash',
		'featured_image'        => 'Featured Image',
		'set_featured_image'    => 'Set featured image',
		'remove_featured_image' => 'Remove featured image',
		'use_featured_image'    => 'Use as featured image',
		'insert_into_item'      => 'Insert into Maintenance Record',
		'uploaded_to_this_item' => 'Uploaded to this Maintenance Record',
		'items_list'            => 'Maintenance Records list',
		'items_list_navigation' => 'Maintenance Records list navigation',
		'filter_items_list'     => 'Filter Maintenance Records list',
	);

	$maintenance_record_args = array(
		'rewrite'				=> array('slug' => 'maintenance-records'),
		'label'                 => 'Maintenance Record',
		'description'           => 'This post type will hold the details of all the maintenance records for Apartment',
		'labels'                => $maintenance_record_labels,
		'supports'              => array('title', 'editor', 'thumbnail', 'comments', 'revisions', 'custom-fields', 'page-attributes', 'excerpt'),
		'taxonomies'            => array('category', 'post_tag', 'maintenance-record'),
		'hierarchical'          => false,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'maintenance-record',
		'map_meta_cap'			=> true,
		'menu_icon'				=> 'dashicons-archive',
		'show_in_rest'          => true, // WP Block Editor
		// 'rest_controller_class' => 'WP_REST_ActionItems_Controller',
	);

	$repair_record_labels = array(
		'name'                  => 'Repair Records',
		'singular_name'         => 'Repair Record',
		'menu_name'             => 'Repair Records',
		'name_admin_bar'        => 'Repair Record',
		'archives'              => 'Repair Record Archives',
		'attributes'            => 'Repair Record Attributes',
		'parent_item_colon'     => 'Parent Repair Record:',
		'all_items'             => 'All Repair Records',
		'add_new_item'          => 'Add New Repair Record',
		'add_new'               => 'Add Repair Record',
		'new_item'              => 'New Repair Record',
		'edit_item'             => 'Edit Repair Record',
		'update_item'           => 'Update Repair Record',
		'view_item'             => 'View Repair Record',
		'view_items'            => 'View Repair Records',
		'search_items'          => 'Search Repair Record',
		'not_found'             => 'Not found',
		'not_found_in_trash'    => 'Not found in Trash',
		'featured_image'        => 'Featured Image',
		'set_featured_image'    => 'Set featured image',
		'remove_featured_image' => 'Remove featured image',
		'use_featured_image'    => 'Use as featured image',
		'insert_into_item'      => 'Insert into Repair Record',
		'uploaded_to_this_item' => 'Uploaded to this Repair Record',
		'items_list'            => 'Repair Records list',
		'items_list_navigation' => 'Repair Records list navigation',
		'filter_items_list'     => 'Filter Repair Records list',
	);

	$repair_record_args = array(
		'rewrite'				=> array('slug' => 'repair-records'),
		'label'                 => 'Repair Record',
		'description'           => 'This post type will hold the details of all the repair records for Apartment',
		'labels'                => $repair_record_labels,
		'supports'              => array('title', 'editor', 'thumbnail', 'comments', 'revisions', 'custom-fields', 'page-attributes', 'excerpt'),
		'taxonomies'            => array('category', 'post_tag', 'repair-record'),
		'hierarchical'          => false,
		'public'                => false,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,
		'exclude_from_search'   => false,
		'publicly_queryable'    => true,
		'capability_type'       => 'repair-record',
		'map_meta_cap'			=> true,
		'menu_icon'				=> 'dashicons-hammer',
		'show_in_rest'          => true, // WP Block Editor
		// 'rest_controller_class' => 'WP_REST_ActionItems_Controller',
	);

	register_post_type('actionitem', $action_item_args);
	register_post_type('transaction', $transaction_args);
	register_post_type('passbook', $passbook_args);
	register_post_type('bulletin', $bulletin_args);
	register_post_type('pending-payment', $pending_payments_args);
	register_post_type('transaction-audit', $transaction_audit_args);
	register_post_type('maintenance-record', $maintenance_record_args);
	register_post_type('repair-record', $repair_record_args);
}

add_action('init', 'custom_post_type', 0);
